version: "3"

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    tty: true
    build: ./requirements/nginx/.
    ports:
      - "8080:8000"
    volumes:
      - ./:/Users/eugenedecorce/Desktop/42/Docker
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    tty: true
    build: ./requirements/wordpress/.
    volumes:
      - ./:/Users/eugenedecorce/Desktop/42/Docker
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    tty: true
    build: ./requirements/mariadb/.
    volumes:
      - ./:/Users/eugenedecorce/Desktop/42/Docker
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
